// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"chunkof_Tokinoki","status":true,"description":"","parameters":{}},
{"name":"DevToolsManage","status":false,"description":"デベロッパツール管理プラグイン","parameters":{"開始時に起動":"OFF","常に前面表示":"OFF","デベロッパツール表示位置":"0,0,800,600"}}
];
